# See https://github.com/actions/labeler

docs:
  - changed-files:
      - any-glob-to-any-file: docs/**

core:
  - changed-files:
      - any-glob-to-any-file: packages/core/**

starlight:
  - changed-files:
      - any-glob-to-any-file: packages/starlight/**
